// File generated by FlutterFire CLI, then hardened to avoid committing secrets.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Reads a compile-time define or falls back to the provided value.
/// If both are empty, throws a clear error at runtime.
String _env(String key, String fallback) {
  // We use a switch so the const evaluation happens with literal keys.
  String value;
  switch (key) {
    case 'FIREBASE_API_KEY_WEB':
      value = const String.fromEnvironment('FIREBASE_API_KEY_WEB', defaultValue: '');
      break;
    case 'FIREBASE_API_KEY_ANDROID':
      value = const String.fromEnvironment('FIREBASE_API_KEY_ANDROID', defaultValue: '');
      break;
    case 'FIREBASE_API_KEY_IOS':
      value = const String.fromEnvironment('FIREBASE_API_KEY_IOS', defaultValue: '');
      break;
    case 'FIREBASE_APP_ID_WEB':
      value = const String.fromEnvironment('FIREBASE_APP_ID_WEB', defaultValue: '');
      break;
    case 'FIREBASE_APP_ID_ANDROID':
      value = const String.fromEnvironment('FIREBASE_APP_ID_ANDROID', defaultValue: '');
      break;
    case 'FIREBASE_APP_ID_IOS':
      value = const String.fromEnvironment('FIREBASE_APP_ID_IOS', defaultValue: '');
      break;
    case 'FIREBASE_APP_ID_WINDOWS':
      value = const String.fromEnvironment('FIREBASE_APP_ID_WINDOWS', defaultValue: '');
      break;
    case 'FIREBASE_MESSAGING_SENDER_ID':
      value = const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: '');
      break;
    case 'FIREBASE_PROJECT_ID':
      value = const String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: '');
      break;
    case 'FIREBASE_AUTH_DOMAIN':
      value = const String.fromEnvironment('FIREBASE_AUTH_DOMAIN', defaultValue: '');
      break;
    case 'FIREBASE_STORAGE_BUCKET':
      value = const String.fromEnvironment('FIREBASE_STORAGE_BUCKET', defaultValue: '');
      break;
    case 'FIREBASE_MEASUREMENT_ID_WEB':
      value = const String.fromEnvironment('FIREBASE_MEASUREMENT_ID_WEB', defaultValue: '');
      break;
    case 'FIREBASE_MEASUREMENT_ID_WINDOWS':
      value = const String.fromEnvironment('FIREBASE_MEASUREMENT_ID_WINDOWS', defaultValue: '');
      break;
    case 'FIREBASE_IOS_CLIENT_ID':
      value = const String.fromEnvironment('FIREBASE_IOS_CLIENT_ID', defaultValue: '');
      break;
    case 'FIREBASE_IOS_BUNDLE_ID':
      value = const String.fromEnvironment('FIREBASE_IOS_BUNDLE_ID', defaultValue: '');
      break;
    default:
      value = '';
  }
  if (value.isEmpty) {
    if (fallback.isNotEmpty) return fallback;
    throw UnsupportedError(
      'Missing compile-time define $key. '
      'Pass it via --dart-define $key=... when building.',
    );
  }
  return value;
}

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY_WEB', ''),
        appId: _env('FIREBASE_APP_ID_WEB', '1:957614256068:web:0f801e646284f29a707e91'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '957614256068'),
        projectId: _env('FIREBASE_PROJECT_ID', 'sanaaos'),
        authDomain: _env('FIREBASE_AUTH_DOMAIN', 'sanaaos.firebaseapp.com'),
        storageBucket: _env('FIREBASE_STORAGE_BUCKET', 'sanaaos.firebasestorage.app'),
        measurementId: _env('FIREBASE_MEASUREMENT_ID_WEB', 'G-GRDX5S3V1B'),
      );

  static FirebaseOptions get android => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY_ANDROID', ''),
        appId: _env('FIREBASE_APP_ID_ANDROID', '1:957614256068:android:07534f57d4ffe3dc707e91'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '957614256068'),
        projectId: _env('FIREBASE_PROJECT_ID', 'sanaaos'),
        storageBucket: _env('FIREBASE_STORAGE_BUCKET', 'sanaaos.firebasestorage.app'),
      );

  static FirebaseOptions get ios => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY_IOS', ''),
        appId: _env('FIREBASE_APP_ID_IOS', '1:957614256068:ios:b157e18a222e6706707e91'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '957614256068'),
        projectId: _env('FIREBASE_PROJECT_ID', 'sanaaos'),
        storageBucket: _env('FIREBASE_STORAGE_BUCKET', 'sanaaos.firebasestorage.app'),
        iosClientId: _env('FIREBASE_IOS_CLIENT_ID', '957614256068-rmu43ikme1aat7r6fogdiaml4837frbd.apps.googleusercontent.com'),
        iosBundleId: _env('FIREBASE_IOS_BUNDLE_ID', 'com.soko24.sokoSellerTerminal'),
      );

  static FirebaseOptions get macos => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY_IOS', ''),
        appId: _env('FIREBASE_APP_ID_IOS', '1:957614256068:ios:b157e18a222e6706707e91'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '957614256068'),
        projectId: _env('FIREBASE_PROJECT_ID', 'sanaaos'),
        storageBucket: _env('FIREBASE_STORAGE_BUCKET', 'sanaaos.firebasestorage.app'),
        iosClientId: _env('FIREBASE_IOS_CLIENT_ID', '957614256068-rmu43ikme1aat7r6fogdiaml4837frbd.apps.googleusercontent.com'),
        iosBundleId: _env('FIREBASE_IOS_BUNDLE_ID', 'com.soko24.sokoSellerTerminal'),
      );

  static FirebaseOptions get windows => FirebaseOptions(
        apiKey: _env('FIREBASE_API_KEY_WEB', ''),
        appId: _env('FIREBASE_APP_ID_WINDOWS', '1:957614256068:web:b419ece77a634482707e91'),
        messagingSenderId: _env('FIREBASE_MESSAGING_SENDER_ID', '957614256068'),
        projectId: _env('FIREBASE_PROJECT_ID', 'sanaaos'),
        authDomain: _env('FIREBASE_AUTH_DOMAIN', 'sanaaos.firebaseapp.com'),
        storageBucket: _env('FIREBASE_STORAGE_BUCKET', 'sanaaos.firebasestorage.app'),
        measurementId: _env('FIREBASE_MEASUREMENT_ID_WINDOWS', 'G-GRR8EWQBRF'),
      );
}
