// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB69FGalbnIiQhtTsuaGPkCODLcKut2xAY',
    appId: '1:957614256068:web:0f801e646284f29a707e91',
    messagingSenderId: '957614256068',
    projectId: 'sanaaos',
    authDomain: 'sanaaos.firebaseapp.com',
    storageBucket: 'sanaaos.firebasestorage.app',
    measurementId: 'G-GRDX5S3V1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdA-oYFCtvXJagFsnS5VseIh8bvghgGRA',
    appId: '1:957614256068:android:07534f57d4ffe3dc707e91',
    messagingSenderId: '957614256068',
    projectId: 'sanaaos',
    storageBucket: 'sanaaos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBr3Gxpf0f_2P1ZUk39rGPvOMgRQiKXIgY',
    appId: '1:957614256068:ios:b157e18a222e6706707e91',
    messagingSenderId: '957614256068',
    projectId: 'sanaaos',
    storageBucket: 'sanaaos.firebasestorage.app',
    iosClientId: '957614256068-rmu43ikme1aat7r6fogdiaml4837frbd.apps.googleusercontent.com',
    iosBundleId: 'com.soko24.sokoSellerTerminal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBr3Gxpf0f_2P1ZUk39rGPvOMgRQiKXIgY',
    appId: '1:957614256068:ios:b157e18a222e6706707e91',
    messagingSenderId: '957614256068',
    projectId: 'sanaaos',
    storageBucket: 'sanaaos.firebasestorage.app',
    iosClientId: '957614256068-rmu43ikme1aat7r6fogdiaml4837frbd.apps.googleusercontent.com',
    iosBundleId: 'com.soko24.sokoSellerTerminal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkN592A306GEan8wbrOD4zLymqpr51-g4',
    appId: '1:957614256068:web:b419ece77a634482707e91',
    messagingSenderId: '957614256068',
    projectId: 'sanaaos',
    authDomain: 'sanaaos.firebaseapp.com',
    storageBucket: 'sanaaos.firebasestorage.app',
    measurementId: 'G-GRR8EWQBRF',
  );
}
