import 'ad_templates.dart';

String _contrastText(String bgHex) => contrastText(bgHex);

// ---------------------------------------------------------------------------
// 1. Diagonal Split
// ---------------------------------------------------------------------------
List<CanvasElement> _buildDiagonalLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  final leftHeavy = variant.isEven;
  final textX = leftHeavy ? w * 0.06 : w * 0.52;
  final imgX = leftHeavy ? w * 0.52 : w * 0.06;
  return [
    CanvasElement(
      id: 'diag_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'diag_accent',
      type: 'figure',
      x: leftHeavy ? 0 : w * 0.48,
      y: -h * 0.05,
      width: w * 0.6,
      height: h * 1.1,
      fill: palette.accent,
      rotation: leftHeavy ? -0.18 : 0.18,
      opacity: 0.92,
    ),
    // Soft diagonal shadow strip
    CanvasElement(
      id: 'diag_shadow',
      type: 'figure',
      x: leftHeavy ? w * 0.42 : w * 0.52,
      y: -h * 0.05,
      width: w * 0.08,
      height: h * 1.1,
      fill: '#000000',
      rotation: leftHeavy ? -0.18 : 0.18,
      opacity: 0.10,
    ),
    CanvasElement(
      id: 'diag_image',
      type: 'image',
      src: '',
      x: imgX,
      y: h * 0.16,
      width: w * 0.42,
      height: h * 0.54,
      cornerRadius: 28,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 14,
      shadowBlur: 32,
      opacity: 1.0,
    ),
    // Category pill
    CanvasElement(
      id: 'diag_cat_pill',
      type: 'figure',
      x: textX,
      y: h * 0.18,
      width: w * 0.22,
      height: h * 0.04,
      fill: leftHeavy ? palette.accent : palette.text,
      cornerRadius: h * 0.02,
      opacity: 0.20,
    ),
    CanvasElement(
      id: 'diag_category',
      type: 'text',
      text: category.toUpperCase(),
      x: textX,
      y: h * 0.185,
      width: w * 0.22,
      fontSize: w * 0.024,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: leftHeavy ? palette.accent : palette.text,
      align: 'center',
      letterSpacing: 1.5,
    ),
    CanvasElement(
      id: 'diag_headline',
      type: 'text',
      text: headline,
      x: textX,
      y: h * 0.25,
      width: w * 0.40,
      fontSize: w * 0.072,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: leftHeavy ? palette.text : _contrastText(palette.accent),
      align: 'left',
      lineHeight: 1.05,
    ),
    CanvasElement(
      id: 'diag_line',
      type: 'figure',
      x: textX,
      y: h * 0.47,
      width: w * 0.14,
      height: h * 0.010,
      fill: leftHeavy ? palette.accent : palette.text,
      cornerRadius: 4,
    ),
    CanvasElement(
      id: 'diag_price',
      type: 'text',
      text: 'UGX 99,000',
      x: textX,
      y: h * 0.50,
      width: w * 0.4,
      fontSize: w * 0.058,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: leftHeavy ? palette.accent : palette.text,
      align: 'left',
    ),
    CanvasElement(
      id: 'diag_cta',
      type: 'text',
      text: 'SHOP NOW →',
      x: textX,
      y: h * 0.62,
      width: w * 0.4,
      fontSize: w * 0.034,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: leftHeavy ? palette.text : _contrastText(palette.accent),
      align: 'left',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 2. Magazine Cover
// ---------------------------------------------------------------------------
List<CanvasElement> _buildMagazineLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'mag_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    // Top accent bar
    CanvasElement(
      id: 'mag_top_rule',
      type: 'figure',
      x: w * 0.15,
      y: h * 0.025,
      width: w * 0.7,
      height: 2,
      fill: palette.accent,
      cornerRadius: 1,
      opacity: 0.6,
    ),
    CanvasElement(
      id: 'mag_category',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.05,
      y: h * 0.045,
      width: w * 0.9,
      fontSize: w * 0.026,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
      letterSpacing: 4,
    ),
    CanvasElement(
      id: 'mag_headline',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.09,
      width: w * 0.9,
      fontSize: w * 0.095,
      fontWeight: 'bold',
      fontFamily: 'Playfair Display',
      fill: palette.text,
      align: 'center',
      lineHeight: 1.0,
    ),
    CanvasElement(
      id: 'mag_subtitle',
      type: 'text',
      text: 'The Ultimate Guide',
      x: w * 0.05,
      y: h * 0.225,
      width: w * 0.9,
      fontSize: w * 0.034,
      fontFamily: 'Lato',
      fill: palette.muted,
      align: 'center',
      letterSpacing: 1,
    ),
    // Large editorial image
    CanvasElement(
      id: 'mag_image',
      type: 'image',
      src: '',
      x: w * 0.06,
      y: h * 0.29,
      width: w * 0.88,
      height: h * 0.46,
      cornerRadius: 8,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 12,
      shadowBlur: 28,
      opacity: 1.0,
    ),
    // Bottom divider
    CanvasElement(
      id: 'mag_bottom_rule',
      type: 'figure',
      x: w * 0.35,
      y: h * 0.78,
      width: w * 0.3,
      height: 2,
      fill: palette.accent,
      cornerRadius: 1,
      opacity: 0.5,
    ),
    CanvasElement(
      id: 'mag_byline',
      type: 'text',
      text: 'By {{BUSINESS}}',
      x: w * 0.05,
      y: h * 0.80,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'mag_price',
      type: 'text',
      text: 'UGX 99,000',
      x: w * 0.05,
      y: h * 0.855,
      width: w * 0.9,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'mag_footer',
      type: 'text',
      text: '{{CTA_LINK}}',
      x: w * 0.05,
      y: h * 0.925,
      width: w * 0.9,
      fontSize: w * 0.022,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      opacity: 0.75,
    ),
  ];
}

// ---------------------------------------------------------------------------
// 3. Polaroid Grid
// ---------------------------------------------------------------------------
List<CanvasElement> _buildPolaroidLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'pol_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'pol_frame',
      type: 'figure',
      x: w * 0.08,
      y: h * 0.08,
      width: w * 0.84,
      height: h * 0.72,
      fill: '#ffffff',
      cornerRadius: 4,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 4,
      shadowBlur: 12,
      opacity: 0.15,
    ),
    CanvasElement(
      id: 'pol_image',
      type: 'image',
      src: '',
      x: w * 0.1,
      y: h * 0.1,
      width: w * 0.8,
      height: h * 0.55,
      cornerRadius: 2,
    ),
    CanvasElement(
      id: 'pol_tape1',
      type: 'figure',
      x: w * 0.35,
      y: h * 0.05,
      width: w * 0.15,
      height: h * 0.04,
      fill: palette.accent,
      rotation: -0.08,
      opacity: 0.6,
    ),
    CanvasElement(
      id: 'pol_tape2',
      type: 'figure',
      x: w * 0.55,
      y: h * 0.06,
      width: w * 0.12,
      height: h * 0.035,
      fill: palette.muted,
      rotation: 0.06,
      opacity: 0.5,
    ),
    CanvasElement(
      id: 'pol_caption',
      type: 'text',
      text: headline,
      x: w * 0.1,
      y: h * 0.68,
      width: w * 0.8,
      fontSize: w * 0.045,
      fontWeight: '600',
      fontFamily: 'Pacifico',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'pol_date',
      type: 'text',
      text: category,
      x: w * 0.1,
      y: h * 0.76,
      width: w * 0.8,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'pol_price',
      type: 'text',
      text: 'UGX 99,000',
      x: w * 0.1,
      y: h * 0.85,
      width: w * 0.8,
      fontSize: w * 0.05,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 4. Cinematic Reel
// ---------------------------------------------------------------------------
List<CanvasElement> _buildCinematicLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'cin_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: '#000000',
    ),
    CanvasElement(
      id: 'cin_top_bar',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h * 0.12,
      fill: '#000000',
    ),
    CanvasElement(
      id: 'cin_bottom_bar',
      type: 'figure',
      x: 0,
      y: h * 0.82,
      width: w,
      height: h * 0.18,
      fill: '#000000',
    ),
    CanvasElement(
      id: 'cin_image',
      type: 'image',
      src: '',
      x: 0,
      y: h * 0.12,
      width: w,
      height: h * 0.7,
      cornerRadius: 0,
    ),
    CanvasElement(
      id: 'cin_title',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.03,
      width: w * 0.9,
      fontSize: w * 0.05,
      fontWeight: 'bold',
      fontFamily: 'Bebas Neue',
      fill: '#ffffff',
      align: 'center',
      letterSpacing: 2,
    ),
    CanvasElement(
      id: 'cin_subtitle',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.05,
      y: h * 0.85,
      width: w * 0.9,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: '#ffffff',
      align: 'center',
    ),
    CanvasElement(
      id: 'cin_cta',
      type: 'text',
      text: 'WATCH NOW  ▶',
      x: w * 0.05,
      y: h * 0.92,
      width: w * 0.9,
      fontSize: w * 0.028,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 5. Price Splash
// ---------------------------------------------------------------------------
List<CanvasElement> _buildPriceSplashLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'splash_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'splash_dot1',
      type: 'figure',
      x: w * 0.1,
      y: h * 0.15,
      width: w * 0.04,
      height: w * 0.04,
      fill: palette.accent,
      cornerRadius: w * 0.02,
      opacity: 0.4,
    ),
    CanvasElement(
      id: 'splash_dot2',
      type: 'figure',
      x: w * 0.78,
      y: h * 0.22,
      width: w * 0.06,
      height: w * 0.06,
      fill: palette.accent,
      cornerRadius: w * 0.03,
      opacity: 0.25,
    ),
    CanvasElement(
      id: 'splash_dot3',
      type: 'figure',
      x: w * 0.85,
      y: h * 0.7,
      width: w * 0.035,
      height: w * 0.035,
      fill: palette.accent,
      cornerRadius: w * 0.0175,
      opacity: 0.35,
    ),
    CanvasElement(
      id: 'splash_dot4',
      type: 'figure',
      x: w * 0.12,
      y: h * 0.75,
      width: w * 0.05,
      height: w * 0.05,
      fill: palette.accent,
      cornerRadius: w * 0.025,
      opacity: 0.2,
    ),
    CanvasElement(
      id: 'splash_product',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.25,
      width: w * 0.9,
      fontSize: w * 0.045,
      fontWeight: '600',
      fontFamily: 'Poppins',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'splash_price',
      type: 'text',
      text: 'UGX 99,000',
      x: w * 0.05,
      y: h * 0.38,
      width: w * 0.9,
      fontSize: w * 0.13,
      fontWeight: 'bold',
      fontFamily: 'Anton',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'splash_category',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.05,
      y: h * 0.55,
      width: w * 0.9,
      fontSize: w * 0.03,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      letterSpacing: 2,
    ),
    CanvasElement(
      id: 'splash_cta_bg',
      type: 'figure',
      x: w * 0.25,
      y: h * 0.7,
      width: w * 0.5,
      height: h * 0.1,
      fill: palette.accent,
      cornerRadius: h * 0.05,
    ),
    CanvasElement(
      id: 'splash_cta',
      type: 'text',
      text: 'BUY NOW',
      x: w * 0.25,
      y: h * 0.725,
      width: w * 0.5,
      fontSize: w * 0.04,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 6. Testimonial Card
// ---------------------------------------------------------------------------
List<CanvasElement> _buildTestimonialLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'test_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'test_quote1',
      type: 'text',
      text: '“',
      x: w * 0.05,
      y: h * 0.02,
      width: w * 0.2,
      fontSize: w * 0.18,
      fontWeight: 'bold',
      fontFamily: 'Playfair Display',
      fill: palette.accent,
      align: 'left',
      opacity: 0.35,
    ),
    CanvasElement(
      id: 'test_quote2',
      type: 'text',
      text: '”',
      x: w * 0.75,
      y: h * 0.55,
      width: w * 0.2,
      fontSize: w * 0.18,
      fontWeight: 'bold',
      fontFamily: 'Playfair Display',
      fill: palette.accent,
      align: 'right',
      opacity: 0.35,
    ),
    CanvasElement(
      id: 'test_avatar',
      type: 'image',
      src: '',
      x: w * 0.35,
      y: h * 0.15,
      width: w * 0.3,
      height: w * 0.3,
      cornerRadius: w * 0.15,
    ),
    CanvasElement(
      id: 'test_review',
      type: 'text',
      text: 'This is the best product I have ever bought. Highly recommend!',
      x: w * 0.1,
      y: h * 0.45,
      width: w * 0.8,
      fontSize: w * 0.04,
      fontFamily: 'Merriweather',
      fill: palette.text,
      align: 'center',
      lineHeight: 1.4,
    ),
    CanvasElement(
      id: 'test_name',
      type: 'text',
      text: 'Jane Nakato',
      x: w * 0.1,
      y: h * 0.62,
      width: w * 0.8,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'test_stars',
      type: 'text',
      text: '★★★★★',
      x: w * 0.1,
      y: h * 0.7,
      width: w * 0.8,
      fontSize: w * 0.055,
      fill: '#fbbf24',
      align: 'center',
    ),
    CanvasElement(
      id: 'test_cta',
      type: 'text',
      text: 'Try PRODUCT NAME today',
      x: w * 0.1,
      y: h * 0.82,
      width: w * 0.8,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 7. Comparison Table
// ---------------------------------------------------------------------------
List<CanvasElement> _buildComparisonLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'comp_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'comp_left_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w * 0.5,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'comp_right_bg',
      type: 'figure',
      x: w * 0.5,
      y: 0,
      width: w * 0.5,
      height: h,
      fill: palette.accent,
      opacity: 0.12,
    ),
    CanvasElement(
      id: 'comp_divider',
      type: 'figure',
      x: w * 0.495,
      y: h * 0.1,
      width: w * 0.01,
      height: h * 0.8,
      fill: palette.muted,
      cornerRadius: w * 0.005,
      opacity: 0.4,
    ),
    CanvasElement(
      id: 'comp_before_label',
      type: 'text',
      text: 'BEFORE',
      x: w * 0.05,
      y: h * 0.06,
      width: w * 0.4,
      fontSize: w * 0.04,
      fontWeight: 'bold',
      fontFamily: 'Oswald',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'comp_after_label',
      type: 'text',
      text: 'AFTER',
      x: w * 0.55,
      y: h * 0.06,
      width: w * 0.4,
      fontSize: w * 0.04,
      fontWeight: 'bold',
      fontFamily: 'Oswald',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'comp_left_image',
      type: 'image',
      src: '',
      x: w * 0.05,
      y: h * 0.15,
      width: w * 0.4,
      height: h * 0.35,
      cornerRadius: 12,
    ),
    CanvasElement(
      id: 'comp_right_image',
      type: 'image',
      src: '',
      x: w * 0.55,
      y: h * 0.15,
      width: w * 0.4,
      height: h * 0.35,
      cornerRadius: 12,
    ),
    CanvasElement(
      id: 'comp_headline',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.55,
      width: w * 0.9,
      fontSize: w * 0.055,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'comp_bullet',
      type: 'text',
      text: '✓ Better Quality  ·  ✓ Best Price  ·  ✓ Fast Delivery',
      x: w * 0.05,
      y: h * 0.68,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'comp_cta',
      type: 'text',
      text: 'SHOP NOW →',
      x: w * 0.05,
      y: h * 0.82,
      width: w * 0.9,
      fontSize: w * 0.04,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 8. QR Code Promo
// ---------------------------------------------------------------------------
List<CanvasElement> _buildQrPromoLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'qr_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'qr_frame',
      type: 'figure',
      x: w * 0.25,
      y: h * 0.1,
      width: w * 0.5,
      height: w * 0.5,
      fill: '#ffffff',
      cornerRadius: 16,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 6,
      shadowBlur: 20,
      opacity: 0.12,
    ),
    CanvasElement(
      id: 'qr_placeholder',
      type: 'image',
      src: '',
      x: w * 0.28,
      y: h * 0.12,
      width: w * 0.44,
      height: w * 0.44,
      cornerRadius: 8,
    ),
    CanvasElement(
      id: 'qr_headline',
      type: 'text',
      text: 'Scan & Shop',
      x: w * 0.05,
      y: h * 0.52,
      width: w * 0.9,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'qr_product',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.62,
      width: w * 0.9,
      fontSize: w * 0.04,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'qr_price',
      type: 'text',
      text: 'UGX 99,000',
      x: w * 0.05,
      y: h * 0.7,
      width: w * 0.9,
      fontSize: w * 0.06,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'qr_biz',
      type: 'text',
      text: '{{BUSINESS}}',
      x: w * 0.05,
      y: h * 0.8,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      opacity: 0.8,
    ),
    CanvasElement(
      id: 'qr_footer',
      type: 'text',
      text: '{{CTA_LINK}}',
      x: w * 0.05,
      y: h * 0.9,
      width: w * 0.9,
      fontSize: w * 0.025,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      opacity: 0.6,
    ),
  ];
}

// ---------------------------------------------------------------------------
// 9. Event Countdown
// ---------------------------------------------------------------------------
List<CanvasElement> _buildCountdownLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  final boxW = w * 0.18;
  final boxH = h * 0.14;
  final startX = w * 0.09;
  final gap = w * 0.04;
  return [
    CanvasElement(
      id: 'cnt_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'cnt_title',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.1,
      width: w * 0.9,
      fontSize: w * 0.065,
      fontWeight: 'bold',
      fontFamily: 'Bebas Neue',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'cnt_sub',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.05,
      y: h * 0.2,
      width: w * 0.9,
      fontSize: w * 0.03,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
      letterSpacing: 2,
    ),
    // DD
    CanvasElement(
      id: 'cnt_dd_box',
      type: 'figure',
      x: startX,
      y: h * 0.32,
      width: boxW,
      height: boxH,
      fill: palette.accent,
      cornerRadius: 8,
    ),
    CanvasElement(
      id: 'cnt_dd_num',
      type: 'text',
      text: '12',
      x: startX,
      y: h * 0.345,
      width: boxW,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'cnt_dd_label',
      type: 'text',
      text: 'DD',
      x: startX,
      y: h * 0.48,
      width: boxW,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    // HH
    CanvasElement(
      id: 'cnt_hh_box',
      type: 'figure',
      x: startX + boxW + gap,
      y: h * 0.32,
      width: boxW,
      height: boxH,
      fill: palette.accent,
      cornerRadius: 8,
    ),
    CanvasElement(
      id: 'cnt_hh_num',
      type: 'text',
      text: '04',
      x: startX + boxW + gap,
      y: h * 0.345,
      width: boxW,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'cnt_hh_label',
      type: 'text',
      text: 'HH',
      x: startX + boxW + gap,
      y: h * 0.48,
      width: boxW,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    // MM
    CanvasElement(
      id: 'cnt_mm_box',
      type: 'figure',
      x: startX + (boxW + gap) * 2,
      y: h * 0.32,
      width: boxW,
      height: boxH,
      fill: palette.accent,
      cornerRadius: 8,
    ),
    CanvasElement(
      id: 'cnt_mm_num',
      type: 'text',
      text: '36',
      x: startX + (boxW + gap) * 2,
      y: h * 0.345,
      width: boxW,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'cnt_mm_label',
      type: 'text',
      text: 'MM',
      x: startX + (boxW + gap) * 2,
      y: h * 0.48,
      width: boxW,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    // SS
    CanvasElement(
      id: 'cnt_ss_box',
      type: 'figure',
      x: startX + (boxW + gap) * 3,
      y: h * 0.32,
      width: boxW,
      height: boxH,
      fill: palette.accent,
      cornerRadius: 8,
    ),
    CanvasElement(
      id: 'cnt_ss_num',
      type: 'text',
      text: '48',
      x: startX + (boxW + gap) * 3,
      y: h * 0.345,
      width: boxW,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'cnt_ss_label',
      type: 'text',
      text: 'SS',
      x: startX + (boxW + gap) * 3,
      y: h * 0.48,
      width: boxW,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'cnt_info',
      type: 'text',
      text: '📍 Kampala, Uganda  ·  🗓️ Saturday, 1 June 2025',
      x: w * 0.05,
      y: h * 0.6,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'cnt_cta_bg',
      type: 'figure',
      x: w * 0.25,
      y: h * 0.75,
      width: w * 0.5,
      height: h * 0.1,
      fill: palette.accent,
      cornerRadius: h * 0.05,
    ),
    CanvasElement(
      id: 'cnt_cta',
      type: 'text',
      text: 'RSVP NOW',
      x: w * 0.25,
      y: h * 0.775,
      width: w * 0.5,
      fontSize: w * 0.04,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 10. Team Spotlight
// ---------------------------------------------------------------------------
List<CanvasElement> _buildTeamLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  final avatarSize = w * 0.18;
  final gap = w * 0.04;
  final startX = w * 0.5 - (avatarSize * 2 + gap * 1.5);
  return [
    CanvasElement(
      id: 'team_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'team_headline',
      type: 'text',
      text: 'Meet Our Team',
      x: w * 0.05,
      y: h * 0.08,
      width: w * 0.9,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'team_tagline',
      type: 'text',
      text: '{{TAGLINE}}',
      x: w * 0.05,
      y: h * 0.18,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    // Avatar 1
    CanvasElement(
      id: 'team_a1',
      type: 'image',
      src: '',
      x: startX,
      y: h * 0.28,
      width: avatarSize,
      height: avatarSize,
      cornerRadius: avatarSize / 2,
    ),
    CanvasElement(
      id: 'team_n1',
      type: 'text',
      text: 'Alex',
      x: startX,
      y: h * 0.28 + avatarSize + h * 0.02,
      width: avatarSize,
      fontSize: w * 0.032,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    // Avatar 2
    CanvasElement(
      id: 'team_a2',
      type: 'image',
      src: '',
      x: startX + avatarSize + gap,
      y: h * 0.28,
      width: avatarSize,
      height: avatarSize,
      cornerRadius: avatarSize / 2,
    ),
    CanvasElement(
      id: 'team_n2',
      type: 'text',
      text: 'Blessing',
      x: startX + avatarSize + gap,
      y: h * 0.28 + avatarSize + h * 0.02,
      width: avatarSize,
      fontSize: w * 0.032,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    // Avatar 3
    CanvasElement(
      id: 'team_a3',
      type: 'image',
      src: '',
      x: startX + (avatarSize + gap) * 2,
      y: h * 0.28,
      width: avatarSize,
      height: avatarSize,
      cornerRadius: avatarSize / 2,
    ),
    CanvasElement(
      id: 'team_n3',
      type: 'text',
      text: 'Chris',
      x: startX + (avatarSize + gap) * 2,
      y: h * 0.28 + avatarSize + h * 0.02,
      width: avatarSize,
      fontSize: w * 0.032,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    // Avatar 4
    CanvasElement(
      id: 'team_a4',
      type: 'image',
      src: '',
      x: startX + (avatarSize + gap) * 3,
      y: h * 0.28,
      width: avatarSize,
      height: avatarSize,
      cornerRadius: avatarSize / 2,
    ),
    CanvasElement(
      id: 'team_n4',
      type: 'text',
      text: 'Diana',
      x: startX + (avatarSize + gap) * 3,
      y: h * 0.28 + avatarSize + h * 0.02,
      width: avatarSize,
      fontSize: w * 0.032,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'team_cta',
      type: 'text',
      text: 'Visit {{BUSINESS}} today',
      x: w * 0.05,
      y: h * 0.75,
      width: w * 0.9,
      fontSize: w * 0.04,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 11. Product Carousel
// ---------------------------------------------------------------------------
List<CanvasElement> _buildCarouselLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'car_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'car_header',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h * 0.1,
      fill: palette.accent,
    ),
    CanvasElement(
      id: 'car_header_text',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.025,
      width: w * 0.9,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'car_main_image',
      type: 'image',
      src: '',
      x: w * 0.05,
      y: h * 0.14,
      width: w * 0.9,
      height: h * 0.48,
      cornerRadius: 16,
    ),
    CanvasElement(
      id: 'car_thumb1',
      type: 'image',
      src: '',
      x: w * 0.08,
      y: h * 0.66,
      width: w * 0.24,
      height: h * 0.18,
      cornerRadius: 10,
    ),
    CanvasElement(
      id: 'car_thumb2',
      type: 'image',
      src: '',
      x: w * 0.38,
      y: h * 0.66,
      width: w * 0.24,
      height: h * 0.18,
      cornerRadius: 10,
    ),
    CanvasElement(
      id: 'car_thumb3',
      type: 'image',
      src: '',
      x: w * 0.68,
      y: h * 0.66,
      width: w * 0.24,
      height: h * 0.18,
      cornerRadius: 10,
    ),
    CanvasElement(
      id: 'car_hint',
      type: 'text',
      text: 'Swipe to explore →',
      x: w * 0.05,
      y: h * 0.88,
      width: w * 0.9,
      fontSize: w * 0.035,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 12. Service Process
// ---------------------------------------------------------------------------
List<CanvasElement> _buildProcessLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  final circleSize = w * 0.16;
  final startX = w * 0.12;
  final gap = w * 0.16;
  return [
    CanvasElement(
      id: 'proc_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'proc_title',
      type: 'text',
      text: 'How It Works',
      x: w * 0.05,
      y: h * 0.08,
      width: w * 0.9,
      fontSize: w * 0.065,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'center',
    ),
    // Connector lines
    CanvasElement(
      id: 'proc_line1',
      type: 'figure',
      x: startX + circleSize,
      y: h * 0.28 + circleSize / 2 - 2,
      width: gap,
      height: 4,
      fill: palette.accent,
      cornerRadius: 2,
      opacity: 0.5,
    ),
    CanvasElement(
      id: 'proc_line2',
      type: 'figure',
      x: startX + circleSize + gap + circleSize,
      y: h * 0.28 + circleSize / 2 - 2,
      width: gap,
      height: 4,
      fill: palette.accent,
      cornerRadius: 2,
      opacity: 0.5,
    ),
    // Circle 1
    CanvasElement(
      id: 'proc_c1',
      type: 'figure',
      x: startX,
      y: h * 0.28,
      width: circleSize,
      height: circleSize,
      fill: palette.accent,
      cornerRadius: circleSize / 2,
    ),
    CanvasElement(
      id: 'proc_n1',
      type: 'text',
      text: '1',
      x: startX,
      y: h * 0.28 + circleSize * 0.22,
      width: circleSize,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'proc_l1',
      type: 'text',
      text: 'Order',
      x: startX - gap * 0.2,
      y: h * 0.28 + circleSize + h * 0.02,
      width: circleSize + gap * 0.4,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    // Circle 2
    CanvasElement(
      id: 'proc_c2',
      type: 'figure',
      x: startX + circleSize + gap,
      y: h * 0.28,
      width: circleSize,
      height: circleSize,
      fill: palette.accent,
      cornerRadius: circleSize / 2,
    ),
    CanvasElement(
      id: 'proc_n2',
      type: 'text',
      text: '2',
      x: startX + circleSize + gap,
      y: h * 0.28 + circleSize * 0.22,
      width: circleSize,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'proc_l2',
      type: 'text',
      text: 'Pay',
      x: startX + circleSize + gap - gap * 0.2,
      y: h * 0.28 + circleSize + h * 0.02,
      width: circleSize + gap * 0.4,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    // Circle 3
    CanvasElement(
      id: 'proc_c3',
      type: 'figure',
      x: startX + (circleSize + gap) * 2,
      y: h * 0.28,
      width: circleSize,
      height: circleSize,
      fill: palette.accent,
      cornerRadius: circleSize / 2,
    ),
    CanvasElement(
      id: 'proc_n3',
      type: 'text',
      text: '3',
      x: startX + (circleSize + gap) * 2,
      y: h * 0.28 + circleSize * 0.22,
      width: circleSize,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'proc_l3',
      type: 'text',
      text: 'Receive',
      x: startX + (circleSize + gap) * 2 - gap * 0.2,
      y: h * 0.28 + circleSize + h * 0.02,
      width: circleSize + gap * 0.4,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'proc_footer',
      type: 'text',
      text: '{{BUSINESS}} — Trusted by thousands',
      x: w * 0.05,
      y: h * 0.75,
      width: w * 0.9,
      fontSize: w * 0.035,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 13. Review Stars
// ---------------------------------------------------------------------------
List<CanvasElement> _buildReviewStarsLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'rs_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'rs_stars',
      type: 'text',
      text: '★★★★★',
      x: w * 0.05,
      y: h * 0.1,
      width: w * 0.9,
      fontSize: w * 0.08,
      fill: '#fbbf24',
      align: 'center',
    ),
    CanvasElement(
      id: 'rs_headline',
      type: 'text',
      text: 'Customer Favorite',
      x: w * 0.05,
      y: h * 0.22,
      width: w * 0.9,
      fontSize: w * 0.055,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'rs_body',
      type: 'text',
      text: 'Absolutely love this product! Fast delivery and amazing quality. Will definitely order again from {{BUSINESS}}.',
      x: w * 0.1,
      y: h * 0.35,
      width: w * 0.8,
      fontSize: w * 0.038,
      fontFamily: 'Merriweather',
      fill: palette.muted,
      align: 'center',
      lineHeight: 1.5,
    ),
    CanvasElement(
      id: 'rs_author',
      type: 'text',
      text: '— Sarah N., Verified Buyer',
      x: w * 0.05,
      y: h * 0.55,
      width: w * 0.9,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'rs_product',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.65,
      width: w * 0.9,
      fontSize: w * 0.045,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'rs_link',
      type: 'text',
      text: 'Shop now: {{CTA_LINK}}',
      x: w * 0.05,
      y: h * 0.78,
      width: w * 0.9,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      opacity: 0.8,
    ),
  ];
}

// ---------------------------------------------------------------------------
// 14. Location Map
// ---------------------------------------------------------------------------
List<CanvasElement> _buildLocationLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'loc_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'loc_map',
      type: 'image',
      src: '',
      x: w * 0.05,
      y: h * 0.05,
      width: w * 0.9,
      height: h * 0.45,
      cornerRadius: 16,
    ),
    CanvasElement(
      id: 'loc_pin',
      type: 'text',
      text: '📍',
      x: w * 0.42,
      y: h * 0.18,
      width: w * 0.16,
      fontSize: w * 0.14,
      align: 'center',
    ),
    CanvasElement(
      id: 'loc_biz',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.55,
      width: w * 0.9,
      fontSize: w * 0.06,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'loc_address',
      type: 'text',
      text: '{{LOCATION}}',
      x: w * 0.05,
      y: h * 0.64,
      width: w * 0.9,
      fontSize: w * 0.035,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'loc_phone',
      type: 'text',
      text: '📞 {{PHONE}}  ·  💬 {{WHATSAPP}}',
      x: w * 0.05,
      y: h * 0.72,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'loc_hours',
      type: 'text',
      text: 'Mon – Sat  ·  9:00 AM – 6:00 PM',
      x: w * 0.05,
      y: h * 0.8,
      width: w * 0.9,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      opacity: 0.8,
    ),
    CanvasElement(
      id: 'loc_cta_bg',
      type: 'figure',
      x: w * 0.25,
      y: h * 0.88,
      width: w * 0.5,
      height: h * 0.08,
      fill: palette.accent,
      cornerRadius: h * 0.04,
    ),
    CanvasElement(
      id: 'loc_cta',
      type: 'text',
      text: 'GET DIRECTIONS',
      x: w * 0.25,
      y: h * 0.9,
      width: w * 0.5,
      fontSize: w * 0.035,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 15. Holiday Wreath
// ---------------------------------------------------------------------------
List<CanvasElement> _buildHolidayLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'hol_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'hol_wreath1',
      type: 'figure',
      x: w * 0.15,
      y: h * 0.1,
      width: w * 0.7,
      height: w * 0.7,
      fill: palette.accent,
      cornerRadius: w * 0.35,
      opacity: 0.15,
    ),
    CanvasElement(
      id: 'hol_wreath2',
      type: 'figure',
      x: w * 0.2,
      y: h * 0.15,
      width: w * 0.6,
      height: w * 0.6,
      fill: palette.accent,
      cornerRadius: w * 0.3,
      opacity: 0.1,
    ),
    CanvasElement(
      id: 'hol_dot1',
      type: 'figure',
      x: w * 0.42,
      y: h * 0.08,
      width: w * 0.04,
      height: w * 0.04,
      fill: palette.accent,
      cornerRadius: w * 0.02,
      opacity: 0.6,
    ),
    CanvasElement(
      id: 'hol_dot2',
      type: 'figure',
      x: w * 0.55,
      y: h * 0.12,
      width: w * 0.03,
      height: w * 0.03,
      fill: palette.accent,
      cornerRadius: w * 0.015,
      opacity: 0.5,
    ),
    CanvasElement(
      id: 'hol_headline',
      type: 'text',
      text: 'Season\'s Greetings',
      x: w * 0.05,
      y: h * 0.05,
      width: w * 0.9,
      fontSize: w * 0.065,
      fontWeight: 'bold',
      fontFamily: 'Playfair Display',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'hol_image',
      type: 'image',
      src: '',
      x: w * 0.25,
      y: h * 0.22,
      width: w * 0.5,
      height: h * 0.35,
      cornerRadius: 16,
    ),
    CanvasElement(
      id: 'hol_greeting',
      type: 'text',
      text: 'Happy Holidays from {{BUSINESS}}',
      x: w * 0.05,
      y: h * 0.62,
      width: w * 0.9,
      fontSize: w * 0.04,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'hol_price',
      type: 'text',
      text: 'UGX 99,000',
      x: w * 0.05,
      y: h * 0.72,
      width: w * 0.9,
      fontSize: w * 0.06,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'hol_cta',
      type: 'text',
      text: 'Shop the Gift Guide →',
      x: w * 0.05,
      y: h * 0.85,
      width: w * 0.9,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 16. Founder Quote
// ---------------------------------------------------------------------------
List<CanvasElement> _buildFounderLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'found_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'found_quote',
      type: 'text',
      text: '“We started {{BUSINESS}} to bring quality and trust to every doorstep in Uganda.”',
      x: w * 0.08,
      y: h * 0.12,
      width: w * 0.84,
      fontSize: w * 0.05,
      fontWeight: '600',
      fontFamily: 'Merriweather',
      fill: palette.text,
      align: 'center',
      lineHeight: 1.5,
    ),
    CanvasElement(
      id: 'found_avatar',
      type: 'image',
      src: '',
      x: w * 0.35,
      y: h * 0.45,
      width: w * 0.3,
      height: w * 0.3,
      cornerRadius: w * 0.15,
    ),
    CanvasElement(
      id: 'found_name',
      type: 'text',
      text: 'Founder Name',
      x: w * 0.05,
      y: h * 0.68,
      width: w * 0.9,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'found_title',
      type: 'text',
      text: 'Founder & CEO',
      x: w * 0.05,
      y: h * 0.75,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'found_logo',
      type: 'text',
      text: '{{BUSINESS}}',
      x: w * 0.05,
      y: h * 0.85,
      width: w * 0.9,
      fontSize: w * 0.04,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'found_cta',
      type: 'text',
      text: 'Our Story →',
      x: w * 0.05,
      y: h * 0.92,
      width: w * 0.9,
      fontSize: w * 0.03,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 17. Unbox Reveal
// ---------------------------------------------------------------------------
List<CanvasElement> _buildUnboxLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'unbox_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'unbox_box_bottom',
      type: 'figure',
      x: w * 0.2,
      y: h * 0.45,
      width: w * 0.6,
      height: h * 0.35,
      fill: palette.accent,
      cornerRadius: 12,
      opacity: 0.9,
    ),
    CanvasElement(
      id: 'unbox_box_lid',
      type: 'figure',
      x: w * 0.15,
      y: h * 0.38,
      width: w * 0.7,
      height: h * 0.08,
      fill: palette.accent,
      cornerRadius: 8,
      rotation: variant.isEven ? -0.1 : 0.1,
      opacity: 0.85,
    ),
    CanvasElement(
      id: 'unbox_product',
      type: 'image',
      src: '',
      x: w * 0.3,
      y: h * 0.18,
      width: w * 0.4,
      height: h * 0.3,
      cornerRadius: 16,
    ),
    CanvasElement(
      id: 'unbox_conf1',
      type: 'figure',
      x: w * 0.15,
      y: h * 0.2,
      width: w * 0.03,
      height: w * 0.03,
      fill: palette.accent,
      cornerRadius: w * 0.015,
      opacity: 0.6,
    ),
    CanvasElement(
      id: 'unbox_conf2',
      type: 'figure',
      x: w * 0.75,
      y: h * 0.25,
      width: w * 0.04,
      height: w * 0.04,
      fill: palette.accent,
      cornerRadius: w * 0.02,
      opacity: 0.5,
    ),
    CanvasElement(
      id: 'unbox_conf3',
      type: 'figure',
      x: w * 0.2,
      y: h * 0.35,
      width: w * 0.025,
      height: w * 0.025,
      fill: palette.text,
      cornerRadius: w * 0.0125,
      opacity: 0.4,
    ),
    CanvasElement(
      id: 'unbox_conf4',
      type: 'figure',
      x: w * 0.8,
      y: h * 0.15,
      width: w * 0.02,
      height: w * 0.02,
      fill: palette.text,
      cornerRadius: w * 0.01,
      opacity: 0.35,
    ),
    CanvasElement(
      id: 'unbox_headline',
      type: 'text',
      text: 'Unbox Happiness',
      x: w * 0.05,
      y: h * 0.72,
      width: w * 0.9,
      fontSize: w * 0.07,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'unbox_sub',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.82,
      width: w * 0.9,
      fontSize: w * 0.04,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
    CanvasElement(
      id: 'unbox_cta',
      type: 'text',
      text: 'ORDER NOW →',
      x: w * 0.05,
      y: h * 0.9,
      width: w * 0.9,
      fontSize: w * 0.035,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// 18. Notification Card
// ---------------------------------------------------------------------------
List<CanvasElement> _buildNotificationLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    CanvasElement(
      id: 'notif_bg',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h,
      fill: palette.bg,
    ),
    CanvasElement(
      id: 'notif_card',
      type: 'figure',
      x: w * 0.06,
      y: h * 0.2,
      width: w * 0.88,
      height: h * 0.5,
      fill: '#ffffff',
      cornerRadius: 20,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 8,
      shadowBlur: 24,
      opacity: 0.12,
    ),
    CanvasElement(
      id: 'notif_icon',
      type: 'image',
      src: '',
      x: w * 0.12,
      y: h * 0.26,
      width: w * 0.12,
      height: w * 0.12,
      cornerRadius: w * 0.03,
    ),
    CanvasElement(
      id: 'notif_title',
      type: 'text',
      text: headline,
      x: w * 0.28,
      y: h * 0.27,
      width: w * 0.6,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'left',
    ),
    CanvasElement(
      id: 'notif_time',
      type: 'text',
      text: 'Now',
      x: w * 0.28,
      y: h * 0.33,
      width: w * 0.6,
      fontSize: w * 0.028,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'left',
    ),
    CanvasElement(
      id: 'notif_body',
      type: 'text',
      text: 'New offer: PRODUCT NAME is now available at UGX 99,000. Tap to shop!',
      x: w * 0.12,
      y: h * 0.4,
      width: w * 0.76,
      fontSize: w * 0.038,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'left',
      lineHeight: 1.4,
    ),
    CanvasElement(
      id: 'notif_btn1_bg',
      type: 'figure',
      x: w * 0.12,
      y: h * 0.55,
      width: w * 0.35,
      height: h * 0.1,
      fill: palette.accent,
      cornerRadius: 12,
    ),
    CanvasElement(
      id: 'notif_btn1',
      type: 'text',
      text: 'Shop',
      x: w * 0.12,
      y: h * 0.57,
      width: w * 0.35,
      fontSize: w * 0.035,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'notif_btn2_bg',
      type: 'figure',
      x: w * 0.53,
      y: h * 0.55,
      width: w * 0.35,
      height: h * 0.1,
      fill: palette.muted,
      cornerRadius: 12,
      opacity: 0.2,
    ),
    CanvasElement(
      id: 'notif_btn2',
      type: 'text',
      text: 'Dismiss',
      x: w * 0.53,
      y: h * 0.57,
      width: w * 0.35,
      fontSize: w * 0.035,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
  ];
}

// ---------------------------------------------------------------------------
// Export
// ---------------------------------------------------------------------------

/// All v2 layout recipes for the template generator.
final layoutRecipesV2 = <LayoutRecipe>[
  LayoutRecipe('diagonal', 'Diagonal Split', _buildDiagonalLayout),
  LayoutRecipe('magazine', 'Magazine Cover', _buildMagazineLayout),
  LayoutRecipe('polaroid', 'Polaroid Grid', _buildPolaroidLayout),
  LayoutRecipe('cinematic', 'Cinematic Reel', _buildCinematicLayout),
  LayoutRecipe('price_splash', 'Price Splash', _buildPriceSplashLayout),
  LayoutRecipe('testimonial', 'Testimonial Card', _buildTestimonialLayout),
  LayoutRecipe('comparison', 'Comparison Table', _buildComparisonLayout),
  LayoutRecipe('qr_promo', 'QR Code Promo', _buildQrPromoLayout),
  LayoutRecipe('countdown', 'Event Countdown', _buildCountdownLayout),
  LayoutRecipe('team', 'Team Spotlight', _buildTeamLayout),
  LayoutRecipe('carousel', 'Product Carousel', _buildCarouselLayout),
  LayoutRecipe('process', 'Service Process', _buildProcessLayout),
  LayoutRecipe('review_stars', 'Review Stars', _buildReviewStarsLayout),
  LayoutRecipe('location', 'Location Map', _buildLocationLayout),
  LayoutRecipe('holiday', 'Holiday Wreath', _buildHolidayLayout),
  LayoutRecipe('founder', 'Founder Quote', _buildFounderLayout),
  LayoutRecipe('unbox', 'Unbox Reveal', _buildUnboxLayout),
  LayoutRecipe('notification', 'Notification Card', _buildNotificationLayout),
];
