import 'package:flutter/material.dart';

import 'ad_templates.dart';
import 'ad_templates_layouts_v2.dart';

/// Programmatic Studio templates — unique layouts × categories × sizes.
/// Appended to [builtInTemplates] for 100+ total designs.
List<AdTemplate> generateStudioTemplates() {
  final out = <AdTemplate>[];

  final layouts = <LayoutRecipe>[
    const LayoutRecipe('hero', 'Hero Spotlight', _buildHeroLayout),
    const LayoutRecipe('split', 'Split Showcase', _buildSplitLayout),
    const LayoutRecipe('banner', 'Bold Banner', _buildBannerLayout),
    const LayoutRecipe('minimal', 'Clean Minimal', _buildMinimalLayout),
    const LayoutRecipe('story', 'Story Vertical', _buildStoryLayout),
    const LayoutRecipe('badge', 'Corner Badge', _buildBadgeLayout),
    const LayoutRecipe('footer', 'Footer CTA', _buildFooterCtaLayout),
    const LayoutRecipe('luxury', 'Editorial Luxe', _buildLuxuryLayout),
    ...layoutRecipesV2,
  ];

  const categoryMeta = <String, ({String label, List<Color> preview})>{
    'sale': (label: 'Sale', preview: [Color(0xFFdc2626), Color(0xFFfef08a)]),
    'new': (label: 'New Drop', preview: [Color(0xFF0f172a), Color(0xFF0EBE7E)]),
    'promo': (label: 'Promo', preview: [Color(0xFF7c3aed), Color(0xFFf9a8d4)]),
    'event': (label: 'Event', preview: [Color(0xFF1e3a8a), Color(0xFFfbbf24)]),
    'food': (label: 'Food Special', preview: [Color(0xFF1c1917), Color(0xFFea580c)]),
    'fashion': (label: 'Fashion Edit', preview: [Color(0xFF18181b), Color(0xFFf472b6)]),
    'beauty': (label: 'Beauty Glow', preview: [Color(0xFF831843), Color(0xFFfbcfe8)]),
    'tech': (label: 'Tech Launch', preview: [Color(0xFF0f172a), Color(0xFF38bdf8)]),
    'service': (label: 'Service Offer', preview: [Color(0xFF0F1D40), Color(0xFF0EBE7E)]),
    'whatsapp': (label: 'WhatsApp Order', preview: [Color(0xFF14532d), Color(0xFF22c55e)]),
    'delivery': (label: 'Fast Delivery', preview: [Color(0xFF1e40af), Color(0xFF93c5fd)]),
    'booking': (label: 'Book Now', preview: [Color(0xFF4c1d95), Color(0xFFc4b5fd)]),
    'agri': (label: 'Farm Fresh', preview: [Color(0xFF14532d), Color(0xFF86efac)]),
    'health': (label: 'Wellness', preview: [Color(0xFF0e7490), Color(0xFF99f6e4)]),
    'realestate': (label: 'Property', preview: [Color(0xFF334155), Color(0xFFfbbf24)]),
    'professional': (label: 'Business', preview: [Color(0xFFf8fafc), Color(0xFF0a66c2)]),
    'catalog': (label: 'Catalog', preview: [Color(0xFFf1f5f9), Color(0xFF0EBE7E)]),
    'luxury': (label: 'Premium', preview: [Color(0xFF09090b), Color(0xFFd4af37)]),
    'grand': (label: 'Grand Opening', preview: [Color(0xFF7f1d1d), Color(0xFFfacc15)]),
    'minimal': (label: 'Minimal', preview: [Color(0xFFffffff), Color(0xFF0f172a)]),
    // ── New categories for v2 ───────────────────────────────────────────────
    'education': (label: 'Education', preview: [Color(0xFF1e3a5f), Color(0xFFfbbf24)]),
    'transport': (label: 'Transport', preview: [Color(0xFF0f172a), Color(0xFFf97316)]),
    'construction': (label: 'Construction', preview: [Color(0xFF451a03), Color(0xFFfacc15)]),
    'hospitality': (label: 'Hospitality', preview: [Color(0xFF1c1917), Color(0xFFeab308)]),
    'retail': (label: 'Retail', preview: [Color(0xFFf8fafc), Color(0xFFdc2626)]),
    'finance': (label: 'Finance', preview: [Color(0xFF064e3b), Color(0xFF34d399)]),
    'fitness': (label: 'Fitness', preview: [Color(0xFF111827), Color(0xFFec4899)]),
    'auto': (label: 'Auto', preview: [Color(0xFF1e293b), Color(0xFF3b82f6)]),
    'salon': (label: 'Salon', preview: [Color(0xFFfdf2f8), Color(0xFFbe185d)]),
    'pharmacy': (label: 'Pharmacy', preview: [Color(0xFFf0fdf4), Color(0xFF16a34a)]),
    'electronics': (label: 'Electronics', preview: [Color(0xFF030712), Color(0xFF22d3ee)]),
    'boutique': (label: 'Boutique', preview: [Color(0xFFfaf5ff), Color(0xFFa855f7)]),
    'cafe': (label: 'Cafe', preview: [Color(0xFFfff7ed), Color(0xFFea580c)]),
    'photography': (label: 'Photography', preview: [Color(0xFF0a0a0a), Color(0xFFffffff)]),
    'consultancy': (label: 'Consultancy', preview: [Color(0xFFf8fafc), Color(0xFF0a66c2)]),
  };

  const palettes = <({String bg, String accent, String text, String muted})>[
    // ── Premium curated palettes (design direction) ─────────────────────────
    // Cobalt + Coral
    (bg: '#1e3a8a', accent: '#ff6b6b', text: '#ffffff', muted: '#93c5fd'),
    // Emerald + Cream
    (bg: '#064e3b', accent: '#fef3c7', text: '#ffffff', muted: '#6ee7b7'),
    // Royal Purple + Gold
    (bg: '#581c87', accent: '#fbbf24', text: '#ffffff', muted: '#d8b4fe'),
    // Sunset Orange + Deep Navy
    (bg: '#f97316', accent: '#0f172a', text: '#ffffff', muted: '#fed7aa'),
    // Teal + Warm Sand
    (bg: '#115e59', accent: '#f5e6d3', text: '#ffffff', muted: '#5eead4'),
    // Blush + Charcoal
    (bg: '#fce7f3', accent: '#374151', text: '#374151', muted: '#9ca3af'),
    // Deep Indigo + Electric Lime
    (bg: '#312e81', accent: '#a3e635', text: '#ffffff', muted: '#a5b4fc'),
    // Charcoal + Tangerine
    (bg: '#1f2937', accent: '#fb923c', text: '#ffffff', muted: '#9ca3af'),
    // Midnight + Cyan
    (bg: '#0f172a', accent: '#22d3ee', text: '#ffffff', muted: '#94a3b8'),
    // Wine + Peach
    (bg: '#7f1d1d', accent: '#fdba74', text: '#ffffff', muted: '#fca5a5'),
    // ── Brand-friendly fallbacks ────────────────────────────────────────────
    (bg: '#0f172a', accent: '#0EBE7E', text: '#ffffff', muted: '#94a3b8'),
    (bg: '#ffffff', accent: '#0F1D40', text: '#0f172a', muted: '#64748b'),
    (bg: '#dc2626', accent: '#fef08a', text: '#ffffff', muted: '#fecaca'),
    (bg: '#1e3a8a', accent: '#fbbf24', text: '#ffffff', muted: '#93c5fd'),
    (bg: '#14532d', accent: '#86efac', text: '#ffffff', muted: '#bbf7d0'),
    (bg: '#4c1d95', accent: '#f9a8d4', text: '#ffffff', muted: '#e9d5ff'),
    (bg: '#1c1917', accent: '#ea580c', text: '#ffffff', muted: '#a8a29e'),
    (bg: '#09090b', accent: '#d4af37', text: '#ffffff', muted: '#a1a1aa'),
    (bg: '#0e7490', accent: '#99f6e4', text: '#ffffff', muted: '#cffafe'),
    (bg: '#831843', accent: '#fbcfe8', text: '#ffffff', muted: '#f9a8d4'),
  ];

  const sizeKeys = <({String key, double w, double h})>[
    (key: 'sq', w: 1080, h: 1080),
    (key: 'story', w: 1080, h: 1920),
    (key: 'portrait', w: 1080, h: 1350),
    (key: 'fb', w: 1200, h: 630),
    (key: 'banner', w: 1920, h: 1080),
    (key: 'pin', w: 1000, h: 1500),
    (key: 'a5', w: 1748, h: 2480),
    (key: 'a6', w: 1240, h: 1748),
    (key: 'dl', w: 2480, h: 1240),
    (key: 'linkedin', w: 1200, h: 627),
    (key: 'youtube', w: 1280, h: 720),
    (key: 'twitter', w: 1600, h: 900),
  ];

  for (final cat in categoryMeta.entries) {
    for (final layout in layouts) {
      if (cat.key == 'luxury' && layout.id == 'luxury') continue;
      // Deterministic size/palette selection based on composite key so that
      // adding categories or layouts at the end does not shift existing IDs.
      final composite = '${layout.id}_${cat.key}';
      final hash = composite.hashCode.abs();
      final size = sizeKeys[hash % sizeKeys.length];
      final palette = palettes[hash % palettes.length];
      final meta = cat.value;

      final w = size.w;
      final h = size.h;
      final elements = layout.builder(
        w: w,
        h: h,
        palette: palette,
        headline: meta.label.toUpperCase(),
        category: cat.key,
        variant: hash,
      );

      out.add(
        AdTemplate(
          // Stable ID: does not depend on global iteration order.
          id: 'gen_${layout.id}_${cat.key}_${size.key}',
          name: '${meta.label} · ${layout.name}',
          category: cat.key,
          canvasWidth: w,
          canvasHeight: h,
          background: palette.bg,
          previewColors: meta.preview,
          elements: elements,
        ),
      );
    }
  }

  // Extra seasonal / regional specials (unique handcrafted-style via generator)
  const specials = [
    ('ramadan', 'Iftar Special', 'food', '#1e3a5f', '#fbbf24'),
    ('eid', 'Eid Celebration', 'event', '#14532d', '#86efac'),
    ('christmas', 'Holiday Sale', 'sale', '#7f1d1d', '#f87171'),
    ('mothers', "Mother's Day", 'promo', '#9d174d', '#fbcfe8'),
    ('fathers', "Father's Day", 'promo', '#1e3a8a', '#93c5fd'),
    ('valentine', 'Valentine Offer', 'promo', '#be185d', '#fda4af'),
    ('wedding', 'Wedding Season', 'event', '#faf5ff', '#a855f7'),
    ('graduation', 'Graduation', 'promo', '#1e293b', '#38bdf8'),
    ('payday', 'Payday Deals', 'sale', '#0f172a', '#22c55e'),
    ('rainy', 'Rainy Season', 'delivery', '#1e40af', '#60a5fa'),
    ('sunday', 'Sunday Market', 'agri', '#365314', '#a3e635'),
    ('nye', 'New Year', 'event', '#09090b', '#facc15'),
  ];

  for (final (slug, name, category, bg, accent) in specials) {
    final hash = slug.hashCode.abs();
    final size = sizeKeys[hash % sizeKeys.length];
    final w = size.w;
    final h = size.h;
    final palette = (
      bg: bg,
      accent: accent,
      text: contrastText(bg),
      muted: '#94a3b8',
    );
    out.add(
      AdTemplate(
        id: 'gen_special_${slug}_${size.key}',
        name: name,
        category: category,
        canvasWidth: w,
        canvasHeight: h,
        background: bg,
        previewColors: [parseHexColor(bg), parseHexColor(accent)],
        elements: _buildHeroLayout(
          w: w,
          h: h,
          palette: palette,
          headline: name.toUpperCase(),
          category: category,
          variant: hash,
        ),
      ),
    );
  }

  return out;
}

// Re-exported from ad_templates.dart for backward compatibility.
String _contrastText(String bgHex) => contrastText(bgHex);

List<CanvasElement> _buildHeroLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  final imgH = h * 0.50;
  final imgY = h * 0.18;
  final pad = w * 0.06;
  return [
    // Soft top accent bar
    CanvasElement(
      id: 'accent_bar',
      type: 'figure',
      x: pad,
      y: h * 0.045,
      width: w - pad * 2,
      height: h * 0.010,
      fill: palette.accent,
      cornerRadius: h * 0.005,
      opacity: 0.85,
    ),
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: pad,
      y: h * 0.075,
      width: w - pad * 2,
      fontSize: w * 0.062,
      fontWeight: 'bold',
      fontFamily: variant.isEven ? 'Bebas Neue' : 'Montserrat',
      fill: palette.text,
      align: 'center',
      letterSpacing: variant.isEven ? 3 : 0,
    ),
    // Subtle category pill
    CanvasElement(
      id: 'cat_pill',
      type: 'figure',
      x: w * 0.35,
      y: h * 0.135,
      width: w * 0.30,
      height: h * 0.035,
      fill: palette.accent,
      cornerRadius: h * 0.0175,
      opacity: 0.18,
    ),
    CanvasElement(
      id: 'cat_text',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.35,
      y: h * 0.139,
      width: w * 0.30,
      fontSize: w * 0.022,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
      letterSpacing: 2,
    ),
    // Hero product image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: pad,
      y: imgY,
      width: w - pad * 2,
      height: imgH,
      cornerRadius: 28,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 12,
      shadowBlur: 28,
      opacity: 1.0,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: pad,
      y: imgY + imgH + h * 0.035,
      width: w - pad * 2,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 99,000',
      x: pad,
      y: imgY + imgH + h * 0.105,
      width: w - pad * 2,
      fontSize: w * 0.058,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    // Rounded CTA
    CanvasElement(
      id: 'cta_bg',
      type: 'figure',
      x: w * 0.26,
      y: h * 0.855,
      width: w * 0.48,
      height: h * 0.075,
      fill: palette.accent,
      cornerRadius: h * 0.0375,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 6,
      shadowBlur: 16,
      opacity: 0.25,
    ),
    CanvasElement(
      id: 'cta_bg_solid',
      type: 'figure',
      x: w * 0.26,
      y: h * 0.855,
      width: w * 0.48,
      height: h * 0.075,
      fill: palette.accent,
      cornerRadius: h * 0.0375,
    ),
    CanvasElement(
      id: 'cta_text',
      type: 'text',
      text: category == 'whatsapp' ? 'WA: {{WHATSAPP}}' : 'ORDER NOW',
      x: w * 0.26,
      y: h * 0.872,
      width: w * 0.48,
      fontSize: w * 0.030,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'footer',
      type: 'text',
      text: '{{BUSINESS}} · {{CTA_LINK}}',
      x: pad,
      y: h * 0.955,
      width: w - pad * 2,
      fontSize: w * 0.019,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      opacity: 0.75,
    ),
  ];
}

List<CanvasElement> _buildSplitLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  final imageLeft = variant.isOdd;
  final imgX = imageLeft ? w * 0.05 : w * 0.52;
  final textX = imageLeft ? w * 0.52 : w * 0.05;
  return [
    // Full-height split panel with soft tint
    CanvasElement(
      id: 'panel',
      type: 'figure',
      x: imageLeft ? w * 0.5 : 0,
      y: 0,
      width: w * 0.5,
      height: h,
      fill: palette.accent,
      opacity: 0.10,
    ),
    // Accent vertical rule
    CanvasElement(
      id: 'rule',
      type: 'figure',
      x: imageLeft ? w * 0.5 + w * 0.04 : w * 0.46,
      y: h * 0.12,
      width: 4,
      height: h * 0.70,
      fill: palette.accent,
      cornerRadius: 2,
      opacity: 0.5,
    ),
    // Hero product image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: imgX,
      y: h * 0.12,
      width: w * 0.43,
      height: h * 0.58,
      cornerRadius: 24,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 10,
      shadowBlur: 22,
      opacity: 1.0,
    ),
    // Category pill
    CanvasElement(
      id: 'cat_pill',
      type: 'figure',
      x: textX,
      y: h * 0.16,
      width: w * 0.24,
      height: h * 0.04,
      fill: palette.accent,
      cornerRadius: h * 0.02,
      opacity: 0.18,
    ),
    CanvasElement(
      id: 'cat_text',
      type: 'text',
      text: category.toUpperCase(),
      x: textX,
      y: h * 0.166,
      width: w * 0.24,
      fontSize: w * 0.022,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
      letterSpacing: 1.5,
    ),
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: textX,
      y: h * 0.23,
      width: w * 0.4,
      fontSize: w * 0.050,
      fontWeight: 'bold',
      fontFamily: 'Oswald',
      fill: palette.text,
      align: 'left',
      lineHeight: 1.1,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: textX,
      y: h * 0.38,
      width: w * 0.4,
      fontSize: w * 0.030,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'left',
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 150,000',
      x: textX,
      y: h * 0.48,
      width: w * 0.4,
      fontSize: w * 0.052,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'left',
    ),
    CanvasElement(
      id: 'cta_bg',
      type: 'figure',
      x: textX,
      y: h * 0.62,
      width: w * 0.34,
      height: h * 0.085,
      fill: palette.accent,
      cornerRadius: h * 0.0425,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 6,
      shadowBlur: 14,
      opacity: 0.20,
    ),
    CanvasElement(
      id: 'cta_bg_solid',
      type: 'figure',
      x: textX,
      y: h * 0.62,
      width: w * 0.34,
      height: h * 0.085,
      fill: palette.accent,
      cornerRadius: h * 0.0425,
    ),
    CanvasElement(
      id: 'cta_text',
      type: 'text',
      text: 'SHOP NOW',
      x: textX,
      y: h * 0.639,
      width: w * 0.34,
      fontSize: w * 0.028,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'footer',
      type: 'text',
      text: '{{LOCATION}}',
      x: w * 0.05,
      y: h * 0.92,
      width: w * 0.9,
      fontSize: w * 0.021,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      opacity: 0.8,
    ),
  ];
}

List<CanvasElement> _buildBannerLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    // Angled-top banner band
    CanvasElement(
      id: 'top_band',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h * 0.30,
      fill: palette.accent,
    ),
    CanvasElement(
      id: 'top_band_shadow',
      type: 'figure',
      x: 0,
      y: h * 0.30,
      width: w,
      height: h * 0.02,
      fill: '#000000',
      opacity: 0.12,
    ),
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.055,
      width: w * 0.9,
      fontSize: w * 0.065,
      fontWeight: 'bold',
      fontFamily: 'Staatliches',
      fill: _contrastText(palette.accent),
      align: 'center',
      letterSpacing: 2,
    ),
    CanvasElement(
      id: 'sub',
      type: 'text',
      text: 'Limited time only',
      x: w * 0.05,
      y: h * 0.175,
      width: w * 0.9,
      fontSize: w * 0.030,
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
      opacity: 0.9,
    ),
    // Hero product image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: w * 0.08,
      y: h * 0.32,
      width: w * 0.84,
      height: h * 0.40,
      cornerRadius: 24,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 12,
      shadowBlur: 28,
      opacity: 1.0,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: w * 0.05,
      y: h * 0.755,
      width: w * 0.9,
      fontSize: w * 0.040,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 75,000',
      x: w * 0.05,
      y: h * 0.820,
      width: w * 0.9,
      fontSize: w * 0.055,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'cta_text',
      type: 'text',
      text: category == 'delivery' ? 'Free delivery today' : '📞 {{PHONE}}',
      x: w * 0.05,
      y: h * 0.905,
      width: w * 0.9,
      fontSize: w * 0.028,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
  ];
}

List<CanvasElement> _buildMinimalLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    // Accent rule
    CanvasElement(
      id: 'rule',
      type: 'figure',
      x: w * 0.1,
      y: h * 0.07,
      width: w * 0.14,
      height: 5,
      fill: palette.accent,
      cornerRadius: 3,
    ),
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: w * 0.1,
      y: h * 0.095,
      width: w * 0.8,
      fontSize: w * 0.055,
      fontWeight: 'bold',
      fontFamily: 'DM Sans',
      fill: palette.text,
      align: 'left',
      lineHeight: 1.1,
    ),
    // Subtle category label
    CanvasElement(
      id: 'cat_text',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.1,
      y: h * 0.165,
      width: w * 0.8,
      fontSize: w * 0.022,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'left',
      letterSpacing: 2,
    ),
    // Large hero image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: w * 0.1,
      y: h * 0.22,
      width: w * 0.8,
      height: h * 0.50,
      cornerRadius: 20,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 10,
      shadowBlur: 24,
      opacity: 1.0,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: w * 0.1,
      y: h * 0.755,
      width: w * 0.8,
      fontSize: w * 0.038,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'left',
    ),
    // Divider
    CanvasElement(
      id: 'divider',
      type: 'figure',
      x: w * 0.1,
      y: h * 0.815,
      width: w * 0.25,
      height: 2,
      fill: palette.accent,
      cornerRadius: 1,
      opacity: 0.5,
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 120,000',
      x: w * 0.1,
      y: h * 0.835,
      width: w * 0.5,
      fontSize: w * 0.048,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'left',
    ),
    CanvasElement(
      id: 'cta_text',
      type: 'text',
      text: 'Shop now →',
      x: w * 0.55,
      y: h * 0.845,
      width: w * 0.35,
      fontSize: w * 0.026,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'right',
    ),
  ];
}

List<CanvasElement> _buildStoryLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    // Soft gradient-like glow at top
    CanvasElement(
      id: 'glow',
      type: 'figure',
      x: 0,
      y: 0,
      width: w,
      height: h * 0.38,
      fill: palette.accent,
      opacity: 0.18,
    ),
    // Decorative circle behind headline
    CanvasElement(
      id: 'headline_circle',
      type: 'figure',
      x: w * 0.25,
      y: h * 0.03,
      width: w * 0.50,
      height: w * 0.50,
      fill: palette.accent,
      cornerRadius: w * 0.25,
      opacity: 0.12,
    ),
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: w * 0.06,
      y: h * 0.07,
      width: w * 0.88,
      fontSize: w * 0.075,
      fontWeight: 'bold',
      fontFamily: 'Bebas Neue',
      fill: palette.text,
      align: 'center',
      letterSpacing: 2,
    ),
    CanvasElement(
      id: 'sub',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.06,
      y: h * 0.13,
      width: w * 0.88,
      fontSize: w * 0.026,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      letterSpacing: 3,
    ),
    // Tall hero product image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: w * 0.07,
      y: h * 0.19,
      width: w * 0.86,
      height: h * 0.46,
      cornerRadius: 32,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 16,
      shadowBlur: 34,
      opacity: 1.0,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: w * 0.06,
      y: h * 0.67,
      width: w * 0.88,
      fontSize: w * 0.048,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    // Price badge
    CanvasElement(
      id: 'price_bg',
      type: 'figure',
      x: w * 0.18,
      y: h * 0.745,
      width: w * 0.64,
      height: h * 0.06,
      fill: palette.accent,
      cornerRadius: h * 0.03,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 6,
      shadowBlur: 16,
      opacity: 0.25,
    ),
    CanvasElement(
      id: 'price_bg_solid',
      type: 'figure',
      x: w * 0.18,
      y: h * 0.745,
      width: w * 0.64,
      height: h * 0.06,
      fill: palette.accent,
      cornerRadius: h * 0.03,
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 49,000',
      x: w * 0.18,
      y: h * 0.754,
      width: w * 0.64,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'swipe',
      type: 'text',
      text: 'Swipe up to order ↑',
      x: w * 0.06,
      y: h * 0.84,
      width: w * 0.88,
      fontSize: w * 0.032,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
      opacity: 0.85,
    ),
    CanvasElement(
      id: 'footer',
      type: 'text',
      text: '{{WHATSAPP}}',
      x: w * 0.06,
      y: h * 0.92,
      width: w * 0.88,
      fontSize: w * 0.028,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
  ];
}

List<CanvasElement> _buildBadgeLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    // Circular discount badge with shadow
    CanvasElement(
      id: 'badge_shadow',
      type: 'figure',
      x: w * 0.62,
      y: h * 0.04,
      width: w * 0.3,
      height: w * 0.3,
      fill: '#000000',
      cornerRadius: w * 0.15,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 8,
      shadowBlur: 18,
      opacity: 0.18,
    ),
    CanvasElement(
      id: 'badge',
      type: 'figure',
      x: w * 0.62,
      y: h * 0.04,
      width: w * 0.3,
      height: w * 0.3,
      fill: palette.accent,
      cornerRadius: w * 0.15,
    ),
    CanvasElement(
      id: 'badge_text',
      type: 'text',
      text: '-30%',
      x: w * 0.62,
      y: h * 0.10,
      width: w * 0.3,
      fontSize: w * 0.060,
      fontWeight: 'bold',
      fontFamily: 'Bebas Neue',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
    CanvasElement(
      id: 'badge_sub',
      type: 'text',
      text: 'OFF',
      x: w * 0.62,
      y: h * 0.14,
      width: w * 0.3,
      fontSize: w * 0.026,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
      opacity: 0.85,
    ),
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: w * 0.06,
      y: h * 0.08,
      width: w * 0.55,
      fontSize: w * 0.054,
      fontWeight: 'bold',
      fontFamily: 'Montserrat',
      fill: palette.text,
      align: 'left',
      lineHeight: 1.1,
    ),
    // Hero product image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: w * 0.06,
      y: h * 0.22,
      width: w * 0.88,
      height: h * 0.50,
      cornerRadius: 28,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 12,
      shadowBlur: 28,
      opacity: 1.0,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: w * 0.06,
      y: h * 0.745,
      width: w * 0.88,
      fontSize: w * 0.040,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 99,000',
      x: w * 0.06,
      y: h * 0.810,
      width: w * 0.88,
      fontSize: w * 0.055,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'cta_text',
      type: 'text',
      text: 'Tap to order · {{CTA_LINK}}',
      x: w * 0.06,
      y: h * 0.905,
      width: w * 0.88,
      fontSize: w * 0.025,
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
    ),
  ];
}

List<CanvasElement> _buildFooterCtaLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    // Top headline
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: w * 0.05,
      y: h * 0.055,
      width: w * 0.9,
      fontSize: w * 0.055,
      fontWeight: 'bold',
      fontFamily: 'Poppins',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'sub',
      type: 'text',
      text: category.toUpperCase(),
      x: w * 0.05,
      y: h * 0.12,
      width: w * 0.9,
      fontSize: w * 0.024,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      letterSpacing: 2.5,
    ),
    // Large centered product image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: w * 0.10,
      y: h * 0.17,
      width: w * 0.80,
      height: h * 0.52,
      cornerRadius: 28,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 14,
      shadowBlur: 30,
      opacity: 1.0,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: w * 0.05,
      y: h * 0.71,
      width: w * 0.9,
      fontSize: w * 0.038,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 200,000',
      x: w * 0.05,
      y: h * 0.77,
      width: w * 0.9,
      fontSize: w * 0.050,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    // Footer CTA bar with rounded top corners
    CanvasElement(
      id: 'footer_bar',
      type: 'figure',
      x: 0,
      y: h * 0.85,
      width: w,
      height: h * 0.15,
      fill: palette.accent,
      cornerRadius: h * 0.035,
    ),
    CanvasElement(
      id: 'footer_bar_solid',
      type: 'figure',
      x: 0,
      y: h * 0.85 + h * 0.035,
      width: w,
      height: h * 0.115,
      fill: palette.accent,
    ),
    CanvasElement(
      id: 'cta_text',
      type: 'text',
      text: category == 'booking' ? 'BOOK NOW · {{PHONE}}' : 'ORDER · {{WHATSAPP}}',
      x: w * 0.05,
      y: h * 0.895,
      width: w * 0.9,
      fontSize: w * 0.032,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: _contrastText(palette.accent),
      align: 'center',
    ),
  ];
}

List<CanvasElement> _buildLuxuryLayout({
  required double w,
  required double h,
  required palette,
  required String headline,
  required String category,
  required int variant,
}) {
  return [
    // Elegant thin frame with generous inset
    CanvasElement(
      id: 'frame',
      type: 'figure',
      x: w * 0.07,
      y: h * 0.06,
      width: w * 0.86,
      height: h * 0.88,
      fill: 'transparent',
      strokeColor: palette.accent,
      strokeWidth: 2.5,
      cornerRadius: 12,
    ),
    // Corner accents
    CanvasElement(
      id: 'corner_tl',
      type: 'figure',
      x: w * 0.06,
      y: h * 0.05,
      width: w * 0.08,
      height: 3,
      fill: palette.accent,
      cornerRadius: 2,
    ),
    CanvasElement(
      id: 'corner_tl_v',
      type: 'figure',
      x: w * 0.06,
      y: h * 0.05,
      width: 3,
      height: w * 0.08,
      fill: palette.accent,
      cornerRadius: 2,
    ),
    CanvasElement(
      id: 'corner_br',
      type: 'figure',
      x: w * 0.86,
      y: h * 0.95,
      width: w * 0.08,
      height: 3,
      fill: palette.accent,
      cornerRadius: 2,
    ),
    CanvasElement(
      id: 'corner_br_v',
      type: 'figure',
      x: w * 0.94,
      y: h * 0.87,
      width: 3,
      height: w * 0.08,
      fill: palette.accent,
      cornerRadius: 2,
    ),
    CanvasElement(
      id: 'headline',
      type: 'text',
      text: headline,
      x: w * 0.1,
      y: h * 0.10,
      width: w * 0.8,
      fontSize: w * 0.045,
      fontWeight: 'bold',
      fontFamily: 'Cinzel',
      fill: palette.accent,
      align: 'center',
      letterSpacing: 5,
    ),
    // Refined product image
    CanvasElement(
      id: 'product_image',
      type: 'image',
      src: '',
      x: w * 0.14,
      y: h * 0.20,
      width: w * 0.72,
      height: h * 0.46,
      cornerRadius: 8,
      shadowColor: '#000000',
      shadowDx: 0,
      shadowDy: 10,
      shadowBlur: 22,
      opacity: 1.0,
    ),
    CanvasElement(
      id: 'product_name',
      type: 'text',
      text: 'PRODUCT NAME',
      x: w * 0.1,
      y: h * 0.70,
      width: w * 0.8,
      fontSize: w * 0.036,
      fontWeight: '600',
      fontFamily: 'Playfair Display',
      fill: palette.text,
      align: 'center',
    ),
    CanvasElement(
      id: 'divider',
      type: 'figure',
      x: w * 0.38,
      y: h * 0.755,
      width: w * 0.24,
      height: 1.5,
      fill: palette.accent,
      cornerRadius: 1,
      opacity: 0.6,
    ),
    CanvasElement(
      id: 'price',
      type: 'text',
      text: 'UGX 150,000',
      x: w * 0.1,
      y: h * 0.775,
      width: w * 0.8,
      fontSize: w * 0.042,
      fontWeight: 'bold',
      fontFamily: 'Inter',
      fill: palette.accent,
      align: 'center',
    ),
    CanvasElement(
      id: 'footer',
      type: 'text',
      text: '{{BUSINESS}}',
      x: w * 0.1,
      y: h * 0.88,
      width: w * 0.8,
      fontSize: w * 0.022,
      fontWeight: '600',
      fontFamily: 'Inter',
      fill: palette.muted,
      align: 'center',
      letterSpacing: 3,
    ),
  ];
}